version: "3.9"

services:
  api:
    env_file: 
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: serverless-deliluncher-api
    volumes: 
      - ".:/usr/src/app"
    ports:
      - "3001:3000"