service: serverless-deliluncher-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  api:
    handler: api/index.get
    events:
      - httpApi:
          path: /api
          method: GET

custom:
  serverless-offline:
    httpPort: 3000
